### ISSUE TITLE
Ask for version information in requirements.txt

### ISSUE THREAD

**Issue by sam351** [MengzhangLI/STFGNN#33]
Hi, I'm trying to set the environment in `colab`.
I cloned this repo & installed packages with `requirements.txt`
After that, I ran below command as it's mentioned in the `README.md`.
```
python main_4n0_3layer_12T_res.py --config config/PEMS04/individual_3layer_12T.json
```
however, I'm getting `AttributeError`, which seems to be related with `mxnet` version issue

> Traceback (most recent call last):
  File "main_4n0_3layer_12T_res.py", line 27, in <module>
    net = construct_model(config)
  File "/content/STFGNN/utils_4n0_3layer_12T_res.py", line 41, in construct_model
    init=mx.init.Constant(value=adj_mx.tolist()))
  File "/usr/local/lib/python3.7/dist-packages/mxnet/symbol/symbol.py", line 2970, in var
    init = init.dumps()
  File "/usr/local/lib/python3.7/dist-packages/mxnet/initializer.py", line 477, in dumps
    self._kwargs['value'] = val.tolist() if isinstance(val, np.ndarray) else val.asnumpy().tolist()
AttributeError: 'list' object has no attribute 'asnumpy'

I think it may be related with `mxnet` version issue.
Could you clarify **specific version information of each required packge** you used in the project?
Or do you have any other possible cause for that Error?

Thank you in advance :)

**Comment by packer-c** [comment]
I am facing the same problem. Have you solved it?

**Comment by sam351** [comment]
Nope... I'm still waiting for the reply...

**Comment by packer-c** [comment]
I solved it, just change Mxnet version. 
My mxnet =1.4.0; Cuda = 10.0; python=3.7 with Windows.

**Comment by Jaycon98** [comment]
> I solved it, just change Mxnet version. My mxnet =1.4.0; Cuda = 10.0; python=3.7 with Windows.

Is it mxnet-cu100=1.4.0? Could you provide more detailed version information about other packages? I still can't get it to work...   Thanks!
![cf32bb0d674e758e031e88ba37db306](https://github.com/MengzhangLI/STFGNN/assets/116989662/6c4be292-c7d2-4cf1-83ec-71c46a1fc5f0)
